Fog of war mechanic (Bandit)
moonstream-to/degen-trail pull request #1
Opened 2024-04-02 04:28 UTC by zomglings

This pull request introduces the single player fog of war mechanic that we will be using in The Degen Trail.

2024-04-02 14:02 UTC, kellan-simiotics requested changes

2024-04-02 14:02 UTC, kellan-simiotics commented on src/Bandit.sol
> +    function _preRollForNFT(address tokenAddress, uint256 tokenID) internal virtual {}
Should there also be a `preRollForPlayer` ?

2024-04-02 14:02 UTC, kellan-simiotics commented on test/Bandit.t.sol
> +        vm.stopPrank();
Is this test supposed to `rerollForNFT` ?

2024-04-09 23:45 UTC, zomglings commented on src/Bandit.sol
> +    function _preRollForNFT(address tokenAddress, uint256 tokenID) internal virtual {}
Added a comment clarifying why there isn't symmetry between player and NFT - NFT has preroll, but player doesn't.

2024-04-09 23:46 UTC, zomglings commented on test/Bandit.t.sol
> +        vm.stopPrank();
Thank you, fixed.

2024-04-09 23:49 UTC, kellan-simiotics approved these changes
lg

2024-04-09 23:49 UTC, merged